# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('c_id', models.AutoField(db_column='C_ID', primary_key=True, serialize=False)),
                ('cityname', models.CharField(db_column='CityName', max_length=10)),
                ('peopleslivelihoodwater', models.FloatField(blank=True, db_column='PeoplesLivelihoodWater', null=True)),
                ('industrialwater', models.FloatField(blank=True, db_column='IndustrialWater', null=True)),
                ('irrigationwaterdemand', models.FloatField(blank=True, db_column='IrrigationWaterDemand', null=True)),
            ],
            options={
                'db_table': 'City',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Flowobservatory',
            fields=[
                ('fo_id', models.AutoField(db_column='FO_ID', primary_key=True, serialize=False)),
                ('basinidentifier', models.CharField(blank=True, db_column='BasinIdentifier', max_length=10, null=True)),
                ('observatoryname', models.CharField(blank=True, db_column='ObservatoryName', max_length=10, null=True)),
            ],
            options={
                'db_table': 'FlowObservatory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('f_id', models.AutoField(db_column='F_ID', primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(blank=True, db_column='TimeStamp', null=True)),
                ('elementvalue', models.CharField(blank=True, db_column='ElementValue', max_length=10, null=True)),
                ('forecastp', models.FloatField(blank=True, db_column='ForecastP', null=True)),
                ('forecastt', models.FloatField(blank=True, db_column='ForecastT', null=True)),
            ],
            options={
                'db_table': 'Forecast',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Forecastingtime',
            fields=[
                ('ft_id', models.AutoField(db_column='FT_ID', primary_key=True, serialize=False)),
                ('forecastingtime', models.DateTimeField(blank=True, db_column='ForecastingTime', null=True)),
            ],
            options={
                'db_table': 'ForecastingTime',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Irrigationarea',
            fields=[
                ('irr_id', models.AutoField(db_column='IRR_ID', primary_key=True, serialize=False)),
                ('irrigationname', models.CharField(blank=True, db_column='IrrigationName', max_length=10, null=True)),
                ('irrigationarea', models.FloatField(blank=True, db_column='IrrigationArea', null=True)),
                ('fallow', models.IntegerField(blank=True, db_column='Fallow', null=True)),
            ],
            options={
                'db_table': 'IrrigationArea',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Light',
            fields=[
                ('light_id', models.AutoField(db_column='Light_ID', primary_key=True, serialize=False)),
                ('light_1', models.CharField(blank=True, db_column='Light_1', max_length=10, null=True)),
                ('light_2', models.CharField(blank=True, db_column='Light_2', max_length=10, null=True)),
                ('light_3', models.CharField(blank=True, db_column='Light_3', max_length=10, null=True)),
                ('light_4', models.CharField(blank=True, db_column='Light_4', max_length=10, null=True)),
                ('light_5', models.CharField(blank=True, db_column='Light_5', max_length=10, null=True)),
                ('light_6', models.CharField(blank=True, db_column='Light_6', max_length=10, null=True)),
                ('light_7', models.CharField(blank=True, db_column='Light_7', max_length=10, null=True)),
                ('light_8', models.CharField(blank=True, db_column='Light_8', max_length=10, null=True)),
                ('light_9', models.CharField(blank=True, db_column='Light_9', max_length=10, null=True)),
                ('light_10', models.CharField(blank=True, db_column='Light_10', max_length=10, null=True)),
                ('light_11', models.CharField(blank=True, db_column='Light_11', max_length=10, null=True)),
                ('light_12', models.CharField(blank=True, db_column='Light_12', max_length=10, null=True)),
            ],
            options={
                'db_table': 'Light',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('l_id', models.AutoField(db_column='L_ID', primary_key=True, serialize=False)),
                ('locationname', models.CharField(db_column='LocationName', max_length=3)),
            ],
            options={
                'db_table': 'Location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nextreservoirlights',
            fields=[
                ('nrl_id', models.AutoField(db_column='NRL_ID', primary_key=True, serialize=False)),
                ('nextreservoirlights', models.CharField(blank=True, db_column='NextReservoirLights', max_length=10, null=True)),
                ('releasetime', models.DateTimeField(blank=True, db_column='ReleaseTime', null=True)),
            ],
            options={
                'db_table': 'NextReservoirLights',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nextweekp',
            fields=[
                ('nwp_id', models.AutoField(db_column='NWP_ID', primary_key=True, serialize=False)),
                ('nextweekp', models.IntegerField(blank=True, db_column='NextWeekP', null=True)),
            ],
            options={
                'db_table': 'NextWeekP',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prewaterlevel',
            fields=[
                ('pwl_id', models.AutoField(db_column='PWL_ID', primary_key=True, serialize=False)),
                ('predictionwaterlevel_1', models.FloatField(blank=True, db_column='PredictionWaterLevel_1', null=True)),
                ('predictionwaterlevel_2', models.FloatField(blank=True, db_column='PredictionWaterLevel_2', null=True)),
                ('predictionwaterlevel_3', models.FloatField(blank=True, db_column='PredictionWaterLevel_3', null=True)),
                ('predictionwaterlevel_4', models.FloatField(blank=True, db_column='PredictionWaterLevel_4', null=True)),
                ('predictionwaterlevel_5', models.FloatField(blank=True, db_column='PredictionWaterLevel_5', null=True)),
                ('predictionwaterlevel_6', models.FloatField(blank=True, db_column='PredictionWaterLevel_6', null=True)),
                ('predictionwaterlevel_7', models.FloatField(blank=True, db_column='PredictionWaterLevel_7', null=True)),
                ('predictionwaterlevel_8', models.FloatField(blank=True, db_column='PredictionWaterLevel_8', null=True)),
                ('predictionwaterlevel_9', models.FloatField(blank=True, db_column='PredictionWaterLevel_9', null=True)),
                ('predictionwaterlevel_10', models.FloatField(blank=True, db_column='PredictionWaterLevel_10', null=True)),
                ('predictionwaterlevel_11', models.FloatField(blank=True, db_column='PredictionWaterLevel_11', null=True)),
                ('predictionwaterlevel_12', models.FloatField(blank=True, db_column='PredictionWaterLevel_12', null=True)),
            ],
            options={
                'db_table': 'PreWaterLevel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prewaterstoragecapacity',
            fields=[
                ('pwsc_id', models.AutoField(db_column='PWSC_ID', primary_key=True, serialize=False)),
                ('predictionwaterstoragecapacity_1', models.FloatField(blank=True, db_column='PredictionWaterStorageCapacity_1', null=True)),
                ('predictionwaterstoragecapacity_2', models.FloatField(blank=True, db_column='PredictionWaterStorageCapacity_2', null=True)),
                ('predictionwaterstoragecapacity_3', models.FloatField(blank=True, db_column='PredictionWaterStorageCapacity_3', null=True)),
                ('predictionwaterstoragecapacity_4', models.FloatField(blank=True, db_column='PredictionWaterStorageCapacity_4', null=True)),
                ('predictionwaterstoragecapacity_5', models.FloatField(blank=True, db_column='PredictionWaterStorageCapacity_5', null=True)),
                ('predictionwaterstoragecapacity_6', models.FloatField(blank=True, db_column='PredictionWaterStorageCapacity_6', null=True)),
                ('predictionwaterstoragecapacity_7', models.FloatField(blank=True, db_column='PredictionWaterStorageCapacity_7', null=True)),
                ('predictionwaterstoragecapacity_8', models.FloatField(blank=True, db_column='PredictionWaterStorageCapacity_8', null=True)),
                ('predictionwaterstoragecapacity_9', models.FloatField(blank=True, db_column='PredictionWaterStorageCapacity_9', null=True)),
                ('predictionwaterstoragecapacity_10', models.FloatField(blank=True, db_column='PredictionWaterStorageCapacity_10', null=True)),
                ('predictionwaterstoragecapacity_11', models.FloatField(blank=True, db_column='PredictionWaterStorageCapacity_11', null=True)),
                ('predictionwaterstoragecapacity_12', models.FloatField(blank=True, db_column='PredictionWaterStorageCapacity_12', null=True)),
            ],
            options={
                'db_table': 'PreWaterStorageCapacity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Q90',
            fields=[
                ('q90_id', models.AutoField(db_column='Q90_ID', primary_key=True, serialize=False)),
                ('ten_1', models.FloatField(blank=True, db_column='Ten_1', null=True)),
                ('ten_2', models.FloatField(blank=True, db_column='Ten_2', null=True)),
                ('ten_3', models.FloatField(blank=True, db_column='Ten_3', null=True)),
                ('ten_4', models.FloatField(blank=True, db_column='Ten_4', null=True)),
                ('ten_5', models.FloatField(blank=True, db_column='Ten_5', null=True)),
                ('ten_6', models.FloatField(blank=True, db_column='Ten_6', null=True)),
                ('ten_7', models.FloatField(blank=True, db_column='Ten_7', null=True)),
                ('ten_8', models.FloatField(blank=True, db_column='Ten_8', null=True)),
                ('ten_9', models.FloatField(blank=True, db_column='Ten_9', null=True)),
                ('ten_10', models.FloatField(blank=True, db_column='Ten_10', null=True)),
                ('ten_11', models.FloatField(blank=True, db_column='Ten_11', null=True)),
                ('ten_12', models.FloatField(blank=True, db_column='Ten_12', null=True)),
                ('ten_13', models.FloatField(blank=True, db_column='Ten_13', null=True)),
                ('ten_14', models.FloatField(blank=True, db_column='Ten_14', null=True)),
                ('ten_15', models.FloatField(blank=True, db_column='Ten_15', null=True)),
                ('ten_16', models.FloatField(blank=True, db_column='Ten_16', null=True)),
                ('ten_17', models.FloatField(blank=True, db_column='Ten_17', null=True)),
                ('ten_18', models.FloatField(blank=True, db_column='Ten_18', null=True)),
                ('ten_19', models.FloatField(blank=True, db_column='Ten_19', null=True)),
                ('ten_20', models.FloatField(blank=True, db_column='Ten_20', null=True)),
                ('ten_21', models.FloatField(blank=True, db_column='Ten_21', null=True)),
                ('ten_22', models.FloatField(blank=True, db_column='Ten_22', null=True)),
                ('ten_23', models.FloatField(blank=True, db_column='Ten_23', null=True)),
                ('ten_24', models.FloatField(blank=True, db_column='Ten_24', null=True)),
                ('ten_25', models.FloatField(blank=True, db_column='Ten_25', null=True)),
                ('ten_26', models.FloatField(blank=True, db_column='Ten_26', null=True)),
                ('ten_27', models.FloatField(blank=True, db_column='Ten_27', null=True)),
                ('ten_28', models.FloatField(blank=True, db_column='Ten_28', null=True)),
                ('ten_29', models.FloatField(blank=True, db_column='Ten_29', null=True)),
                ('ten_30', models.FloatField(blank=True, db_column='Ten_30', null=True)),
                ('ten_31', models.FloatField(blank=True, db_column='Ten_31', null=True)),
                ('ten_32', models.FloatField(blank=True, db_column='Ten_32', null=True)),
                ('ten_33', models.FloatField(blank=True, db_column='Ten_33', null=True)),
                ('ten_34', models.FloatField(blank=True, db_column='Ten_34', null=True)),
                ('ten_35', models.FloatField(blank=True, db_column='Ten_35', null=True)),
                ('ten_36', models.FloatField(blank=True, db_column='Ten_36', null=True)),
            ],
            options={
                'db_table': 'Q90',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Q95',
            fields=[
                ('q95_id', models.AutoField(db_column='Q95_ID', primary_key=True, serialize=False)),
                ('ten_1', models.FloatField(blank=True, db_column='Ten_1', null=True)),
                ('ten_2', models.FloatField(blank=True, db_column='Ten_2', null=True)),
                ('ten_3', models.FloatField(blank=True, db_column='Ten_3', null=True)),
                ('ten_4', models.FloatField(blank=True, db_column='Ten_4', null=True)),
                ('ten_5', models.FloatField(blank=True, db_column='Ten_5', null=True)),
                ('ten_6', models.FloatField(blank=True, db_column='Ten_6', null=True)),
                ('ten_7', models.FloatField(blank=True, db_column='Ten_7', null=True)),
                ('ten_8', models.FloatField(blank=True, db_column='Ten_8', null=True)),
                ('ten_9', models.FloatField(blank=True, db_column='Ten_9', null=True)),
                ('ten_10', models.FloatField(blank=True, db_column='Ten_10', null=True)),
                ('ten_11', models.FloatField(blank=True, db_column='Ten_11', null=True)),
                ('ten_12', models.FloatField(blank=True, db_column='Ten_12', null=True)),
                ('ten_13', models.FloatField(blank=True, db_column='Ten_13', null=True)),
                ('ten_14', models.FloatField(blank=True, db_column='Ten_14', null=True)),
                ('ten_15', models.FloatField(blank=True, db_column='Ten_15', null=True)),
                ('ten_16', models.FloatField(blank=True, db_column='Ten_16', null=True)),
                ('ten_17', models.FloatField(blank=True, db_column='Ten_17', null=True)),
                ('ten_18', models.FloatField(blank=True, db_column='Ten_18', null=True)),
                ('ten_19', models.FloatField(blank=True, db_column='Ten_19', null=True)),
                ('ten_20', models.FloatField(blank=True, db_column='Ten_20', null=True)),
                ('ten_21', models.FloatField(blank=True, db_column='Ten_21', null=True)),
                ('ten_22', models.FloatField(blank=True, db_column='Ten_22', null=True)),
                ('ten_23', models.FloatField(blank=True, db_column='Ten_23', null=True)),
                ('ten_24', models.FloatField(blank=True, db_column='Ten_24', null=True)),
                ('ten_25', models.FloatField(blank=True, db_column='Ten_25', null=True)),
                ('ten_26', models.FloatField(blank=True, db_column='Ten_26', null=True)),
                ('ten_27', models.FloatField(blank=True, db_column='Ten_27', null=True)),
                ('ten_28', models.FloatField(blank=True, db_column='Ten_28', null=True)),
                ('ten_29', models.FloatField(blank=True, db_column='Ten_29', null=True)),
                ('ten_30', models.FloatField(blank=True, db_column='Ten_30', null=True)),
                ('ten_31', models.FloatField(blank=True, db_column='Ten_31', null=True)),
                ('ten_32', models.FloatField(blank=True, db_column='Ten_32', null=True)),
                ('ten_33', models.FloatField(blank=True, db_column='Ten_33', null=True)),
                ('ten_34', models.FloatField(blank=True, db_column='Ten_34', null=True)),
                ('ten_35', models.FloatField(blank=True, db_column='Ten_35', null=True)),
                ('ten_36', models.FloatField(blank=True, db_column='Ten_36', null=True)),
            ],
            options={
                'db_table': 'Q95',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Regionalwaterregime',
            fields=[
                ('rwr_id', models.AutoField(db_column='RWR_ID', primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_column='TimeStamp')),
                ('reservoirlightsnow', models.CharField(blank=True, db_column='ReservoirLightsNow', max_length=1, null=True)),
            ],
            options={
                'db_table': 'RegionalWaterRegime',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reservoir',
            fields=[
                ('r_id', models.AutoField(db_column='R_ID', primary_key=True, serialize=False)),
                ('reservoiridentifier', models.CharField(db_column='ReservoirIdentifier', max_length=8)),
                ('reservoirname', models.CharField(blank=True, db_column='ReservoirName', max_length=10, null=True)),
            ],
            options={
                'db_table': 'Reservoir',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reservoirstate',
            fields=[
                ('rs_id', models.AutoField(db_column='RS_ID', primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_column='TimeStamp')),
                ('waterlevel', models.FloatField(blank=True, db_column='WaterLevel', null=True)),
                ('effectivewaterstoragecapacity', models.FloatField(blank=True, db_column='EffectiveWaterStorageCapacity', null=True)),
                ('percentageusedinreservoircapacity', models.FloatField(blank=True, db_column='PercentageUsedInReservoirCapacity', null=True)),
                ('maximumcapacity', models.FloatField(blank=True, db_column='MaximumCapacity', null=True)),
            ],
            options={
                'db_table': 'ReservoirState',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rulecurve',
            fields=[
                ('rc_id', models.AutoField(db_column='RC_ID', primary_key=True, serialize=False)),
                ('tendays_no', models.FloatField(blank=True, db_column='TenDays_No', null=True)),
                ('upperlimit', models.FloatField(blank=True, db_column='UpperLimit', null=True)),
                ('midlimit', models.FloatField(blank=True, db_column='MidLimit', null=True)),
                ('lowerlimit', models.FloatField(blank=True, db_column='LowerLimit', null=True)),
                ('seriouslowerlimit', models.FloatField(blank=True, db_column='SeriousLowerLimit', null=True)),
            ],
            options={
                'db_table': 'RuleCurve',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Simreservoirflow',
            fields=[
                ('srf_id', models.AutoField(db_column='SRF_ID', primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(blank=True, db_column='TimeStamp', null=True)),
                ('streamflow', models.FloatField(blank=True, db_column='StreamFlow', null=True)),
                ('planwaterdemand', models.FloatField(blank=True, db_column='PlanWaterDemand', null=True)),
                ('irrigationrequirement', models.FloatField(blank=True, db_column='IrrigationRequirement', null=True)),
                ('waterright', models.FloatField(blank=True, db_column='WaterRight', null=True)),
            ],
            options={
                'db_table': 'SimReservoirFlow',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Waterintakestructures',
            fields=[
                ('wis_id', models.AutoField(db_column='WIS_ID', primary_key=True, serialize=False)),
                ('structuresname', models.CharField(blank=True, db_column='StructuresName', max_length=10, null=True)),
                ('q_downstream', models.FloatField(blank=True, db_column='Q_downstream', null=True)),
                ('maxq', models.FloatField(blank=True, db_column='MaxQ', null=True)),
            ],
            options={
                'db_table': 'WaterIntakeStructures',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Watersupply',
            fields=[
                ('ws_id', models.AutoField(db_column='WS_ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'WaterSupply',
                'managed': False,
            },
        ),
    ]
